version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedback_app
    ports:
      # 将主机的 8000 端口映射到容器的 8000 端口
      # 容器内的应用会监听 Dockerfile 中 PORT 环境变量定义的端口 (默认为 8000)
      - '8000:8000'
    volumes:
      # 将主机当前目录下的 app_database.db 文件挂载到容器的 /app/app_database.db
      # 这样可以持久化 SQLite 数据库
      - ./app_database.db:/app/app_database.db
    env_file:
      # 从项目根目录下的 .env 文件加载环境变量
      - .env
    restart: unless-stopped # 可选：配置容器重启策略
