name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches: ['main'] # Or your desired branch
    # Or trigger on tag creation, releases, etc.
    # tags:
    #   - 'v*.*.*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Path to your Dockerfile and build context
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/<IMAGE_NAME>:${{ github.sha }}
          # You can also use other tags like:
          # tags: |
          #   ghcr.io/${{ github.repository_owner }}/<IMAGE_NAME>:latest
          #   ghcr.io/${{ github.repository_owner }}/<IMAGE_NAME>:${{ github.ref_name }}
          #   ghcr.io/${{ github.repository_owner }}/<IMAGE_NAME>:${{ github.run_id }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
